version: '3'
services:
    devops-registry:
        restart: always
        image: registry:2
        ports:
            - 5000:5000
        environment:
            REGISTRY_HTTP_TLS_CERTIFICATE: /certs/devops-registry.crt
            REGISTRY_HTTP_TLS_KEY: /certs/devops-registry.key
            REGISTRY_AUTH: htpasswd
            REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
            REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
            REGISTRY_STORAGE_DELETE_ENABLED: "true"
        volumes:
            - /registry/data:/var/lib/registry
            - /home/ubuntu/docker/private-registry/certs:/certs
            - /home/ubuntu/docker/private-registry/auth:/auth
        networks:
            extnetwork:
                ipv4_address: 172.21.0.10

    docker-ui:
        restart: always
        image: konradkleine/docker-registry-frontend:v2
        ports:
            - 5001:80
        depends_on:
            - devops-registry
        environment:
            ENV_DOCKER_REGISTRY_HOST: devops-registry
            ENV_DOCKER_REGISTRY_PORT: 5000
            ENV_DOCKER_REGISTRY_USE_SSL: '1'
        networks:
            extnetwork:
                ipv4_address: 172.21.0.11

networks:
    extnetwork:
        ipam:
            config:
            - subnet: 172.21.0.0/16
