web:
    container_name: nginx-web
    image: nginx
    volumes: 
     - ./conf.d:/etc/nginx/conf.d
     - ./static_html:/usr/share/nginx/html
     - ./logs:/var/logs
    ports: 
     - "8081:80"
     - "8082:8082"
