version: '3'
 
services: 
    mysql:
        restart: always
        image: mysql:5.7
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: 123456
        command:
             --character-set-server=utf8
        volumes:
             - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
